/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Logo: typeof import('./src/components/layout/Logo.vue')['default']
    MenuItem: typeof import('./src/components/layout/components/MenuItem.vue')['default']
    Nav: typeof import('./src/components/layout/Nav.vue')['default']
    Router: typeof import('./src/components/layout/Router.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/layout/Setting.vue')['default']
    Siderbar: typeof import('./src/components/layout/Siderbar.vue')['default']
  }
}
